name: Test Components


on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Install packages
        run: yarn
      - name: Run tests
        run: yarn test
